MyLibrary/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls)
]
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

urlpatterns += [
path('', RedirectView.as_view(url='/catalog/')),
]

urlpatterns += static(settings.STATIC_URL,
document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('', views.index, name='index'),
path('books/', views.BookListView.as_view(), name='books'),
path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
path('authors/', views.AuthorListView.as_view(), name='authors'),
path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

catalog/models.py
from django.db import models

# Create your models here.
from django.db.models import Model


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='請輸入書本類別(例如:科學書刊。)')

    def __str__(self):
        return self.name


from django.urls import reverse  # Used to generate URLs by reversing the URL patterns


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='請輸入書本摘要')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='請輸入13碼<a href="https://www.isbn-international.org/content/what-isbn">ISBN 號碼</a>')
    genre = models.ManyToManyField(Genre, help_text='請選擇本書類型')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

import uuid
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='請輸入一個UUID(獨特ID)來代表書:')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', '維護中'),
        ('o', '借出中'),
        ('a', '可借用'),
        ('r', '已預約'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availablity')


    class Meta:
        ordering = ['due_back']


    def __str__(self):
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


from django.db import models


class Language(models.Model):
    name = models.CharField(max_length=200,
                            help_text="請輸入語言(例如:英文,法文,德文...)")
    def __str__(self):
        return self.name

catalog/views.py
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from .models import Book, Author, BookInstance, Genre


def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status ='a')
    num_instances_availiable = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_availiable,
        'num_authors': num_authors,
    }

    # Render th HTML template index.html with the data in context variable
    return render(request, 'index.html', context=context)


from django.views import generic

class BookListView(generic.ListView):
    model = Book


class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        try:
            book = Book.objects.get(pk=primary_key)
        except Book.DoesNotExite:
            raise Http404('Book does not exit')
        return render(request, 'catalog/book_detail.html', context={'book': book})


class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author

    def Author_detail_view(request, primary_key):
        try:
            author = Author.objects.get(pk=primary_key)
        except Author.DoesNotExite:
            raise Http404('Author does not exit')
        return render(request, 'catalog/author_detail.html', context={'author': author})

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <!--Add additional CSS in static file-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container-fluid">
	   <div class ="row">
	       <div class="col-sm-2">
	       {% block sidebar %}
               <ul class="sidebar-nav">
		            <li><a href="{% url 'index' %}">Home</a></li>
		            <li><a href="{% url 'books' %}">All books</a></li>
		            <li><a href="{% url 'authors' %}">All authors</a></li>
	            </ul>
                {% endblock %}
            </div>
                <div class="col-sm-10 ">
                {%  block content %} {% endblock %}
                </div>
        </div>
	</div>

</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ author.title }}</h1>
    <p><strong>First name:</strong> {{ author.first_name }}</p>
    <p><strong>Last name:</strong> {{ author.last_name }}</p>
    <p><strong>Date of birth:</strong> {{ author.date_of_birth }}</p>
    <p><strong>Died:</strong> {{ author.date_of_death }}</p>
    <!--<p><strong>Gener:</strong> {% for genre in author.genre.all %} {{ genre }} {% if not forloop.last %}, {% endif %}{% endfor %}</p>-->
    

{% endblock %}

catalog/templates/catalog/author_list.html
{%  extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {%  if author_list %}
    <ul>
        {%  for author in author_list %}
            <li>
                <a href="{{ author.get_absolute_url }}">{{ author }}</a>
            </li>
        {%  endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

	

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p><strong>Author:</strong> <a href="{% url 'authors' %}">{{ book.author }}</a> 
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Gener:</strong> {% for genre in book.genre.all %} {{ genre}} {% if not forloop.last %}, {% endif %}{% endfor %}</p>
    
    <div style="magin-lef:20px;margin-top:20px;>
	<h4>Copies</h4>
	
	{% for copy in book.bookinstance_set.all %}
	<hr>
	<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}"> {{ copy.get_status_display }}</p>
	{% if copy.status != 'a' %}
	<p><strong>Due to be returned:</strong> {{copy.due_back}}
	</p>
	{% endif %}
	<p><strong>Imprint:</strong> {{ copy.imprint }}
	</p>
	<p class="text-muted"><strong>Id:</strong> {{ copy.id }}
	</p>
    {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{%  extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {%  if book_list %}
    <ul>
        {%  for book in book_list %}
            <li>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>  ({{ book.author }})
            </li>
        {%  endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
   <h1>Local Library Home</h1>
   <p>Welcome to MyLibrary!</p>

   <h2>Dynamic content</h2>
   <p>The library has the following record counts:</p>
   <ul>
     <li><strong>Books:</strong> {{ num_books }}</li>
     <li><strong>Copies:</strong> {{ num_instances }}</li>
     <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
     <li><strong>Authors:</strong> {{ num_authors }}</li>
   </ul>

{% endblock %}